version: '3'

services:
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

  pipelines:
    image: 'pipelines:latest'
    depends_on:
      - 'mongo'
    ports:
      - '80:80'
volumes:
  mongo: